const stories = [
    `" A pandemic has wiped out over 99 percent of humanity, but don't worry. It only spreads to those who know about it. "`,
    `" I twisted and rolled over in bed, then froze as I saw something distinctly not human smile at me through my window. My heart almost stopped when I noticed it was a reflection. "`,
    `"  You get home, tired after a long day's work and ready for a relaxing night alone. You reach for the light switch, but another hand is already there. "`,
    `" I twisted and rolled over in bed, then froze as I saw something distinctly not human smile at me through my window. My heart almost stopped when I noticed it was a reflection. "`,
    `" I have a friend named Charlie. I'm playing at his house but it's cold down here in the basement, I wonder when Charlie will let me go home. "`,
    `"  You hear your mom calling you into the kitchen. As you are heading down the stairs you hear a whisper from the closet saying \"Don't go down there honey, I heard it too.\" "`,
    `" The officer finally got back to me. The call was coming from inside the house. "`,
    `"  You're laying in bed and with your feet dangling out of the covers. You feel a hand grab your feet. "`,
    `"I begin tucking him into bed and he tells me,"Daddy check for monsters under my bed." I look underneath for his amusement and see him, another him, under the bed, staring back at me quivering and whispering,"Daddy there's somebody on my bed."`,
    `" For sale: like-new engagement ring, barely worn, came right off her finger. Finger also for sale for the right offer. "`,
    `" No matter how much we fight, my wife will always prepare my coffee in the morning. Though this time, it did taste a little like almonds. " `,
    `" If you get scared at night, don't keep your eyes closed for too long. There's a reason you're scared, and now you can't see it approach. "`,
    `" The world ending in 2012 wasn't a prophecy, it was a suggestion. We should have listened, but now He's here. "`,
    `"  My wife woke me up last night to tell me there was an intruder in our house. She was murdered by an intruder 2 years ago. "`,
    `"  Nurse's Note: Born 7 pounds 10 ounces, 18 inches long, 32 fully formed teeth. Silent, always smiling. "`,
    `" I love diving into the deepest parts of the ocean where you can't even see the bottom! This time, I can't see the surface, either. "`,
    `" I used a Ouija board yesterday, but I only asked one question and put it away. I got my answer today. It was written in blood on my ceiling. "`,
    `" It's nice that my grandmother calls to check on me, but if she wants to communicate from the other side I wish she wouldn't scream so much. "`,
    `" 'You look like death,' he said, brows furrowed with concern. A wide, wan smile crossed my face, flattered to be recognized, as I hooked him with my scythe and pulled him downward into the abyss. "`,
    `" I like to sing in the shower sometimes. When I got out of the last one, the fogged-up mirror read "YOU HAVE A LOVELY VOICE" I live alone. "`,
    `" We smiled proudly as our daughter went on her bus for her first day of school. Our hearts dropped when the real bus arrived two minutes later. "`,
    `" Don't look behind you. It doesn't like to be seen. ",`, 
    `" Yesterday, I figured out how my curse worked. Apparently, only people in danger can see what I write. "`,
    `"  I just saw my reflection blink. ",`,
    `" Growing up with cats and dogs, I got used to the sounds of scratching at my door while I slept. Now that I live alone, it is much more unsettling. "`,
    `"  The funeral attendees never came out of the catacombs. Something locked the crypt door from the inside. "`, 
    `" She went upstairs to check on her sleeping toddler. The window was open and the bed was empty. " `, 
    `" My girlfriend is scared of horror movies. They make her paranoid, which can be tricky when I'm watching her through her living room window. "`,
    `" I can't move, breathe, speak or hear and it's so dark all day round. "`,
    `" I saw a severed arm in the dumpster. It gave me a thumbs up when I walked by. "`
  ];

  module.exports = stories;
  
